language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: hidden-woodland-36097
  api_key:
    secure: vgShl1dz6dVG6+Q0z95glS4tvCv9k4FeZa84ueBeynpMdietfah4RAh264cFSVZLY6izhMBYwyw4JYWLTHG9iHZUiPbz9ZBe6D1kVczf0YWHuXYMbJg7pbdAVB5Mj4LwSn77tA2LLxA35w3jLRBOaqAkRrm5EqbxhQdJvrLj9Wrv8yj8oN/cmwSkX+EUQ4U7FLSoN7yeTX3NTi0jk3EvXepilwut+zdfcUiie8lFvsA4KHDZ5fw+hRSSs6HP5GF37zabkYw+X9pvr0Vwy5doataQjZTn0goBuYsKa9gZ0kPKtLChi1IMlmd9KTLq/H93nSdnjC+OGGdoXqoMU1cRE7K19EMsIKcKL/hzFpGRfSNEkuWfrq3N3UZNYIvVAhHuj58dgjZJE+P+CVboScu/He4n/AghmbUe76lofEiaPgPH+NB1P5z7TlngVtlU3p6wnglsXfrRmlf1QyMri1jE3zYUkQ+3Q2w3h4maLpdeJxGx6QevaJb/Vj/nPvBddypNZ5fceEnv/EMTbDY0sqZfbM7Lb/FDE0z1haUcSgS06G0v84QxS3BRgs/I22QXFZPbRuSzX1TlJ4uozUUaGcdFhZMxn26z8KcSjIffcfiC4u7udo8+wkqmdOA/8+XG/YQofebDjsKemporATjn57z7/Do59kqAc7i7i48LciLkGlc=
