language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  app: hidden-woodland-36097
  api_key:
    secure: up9cMtf0ISg/u5UkGZDyEEnQHPEaIkVD5iojhXMCLzWs6fG8VlTZy9OSY3mPXwKG+PCnAXVQGFAlianypUzoGFuG2QVvkBxSmDkoX57tMM28EsLYCxUlZb1wESCNwn7MagDcoJpN0DXlvWgvF4ffxdWv1A0o3zmxS1LkApAdI39au7/RYmpvWuXY9XFodx0eqlgk8tJsl6JhQEU1WFQR9UrJ+8jt2r5BSoyG5OJSPVFDeRhXUE2BjhLfLUQEp1Ca4lpyh5j1QNtWZELA4SMZr8HrlbjG9d4SO189TU0RukPqzwjS1TNY/cnXUngAIsoNWzPvo5FcQ5TKeISg3M8WeBzT3SmBwtQTplbDuLhc5N8FkJMBsxJTC5VxUaFm3b9GzyoEEwKkUfqG2ilhgjwe/0Ag27mbEoaak2dTgMTI6FtumXDHvgNV5PJm09Vc8xpHUogYzX286Pd1nAsLym0/IUv/S96F9v7WRPCk1yFFPH59Zx6SYovRqDGS4rf2SbDS1cb+jUJ6yrjKB0/+54otVdxr54Fvg3YMK3ou1F8TQDrB3vpymuPHvTHZI5neeJFLli3ZKfHbksFamx69njFNn0vUnStBvlbn3ZnE/GbhiqZE6+JEdXP4J/8fvgCYpPrnds+TtjQRO+/vwB9c2KPJrZVnGHEYmS0Yd+cd1ZiEbZU=
